#!/bin/bash
# Pipecat Cloud Deployment Guide

echo "=== Pipecat Cloud Deployment ==="
echo ""
echo "Option A: Docker Hub (Recommended)"
echo "1. Export Docker image:"
echo "   docker save pipecat-telesales-agent:latest | gzip > pipecat-agent.tar.gz"
echo ""
echo "2. In Pipecat Cloud Dashboard:"
echo "   - Create New Agent"
echo "   - Runtime: Docker"
echo "   - Image: dsactivi-2/pipecat-telesales-agent:latest"
echo "   - Environment Variables:"
echo "     OPENAI_API_KEY=sk-proj-..."
echo "     DEEPGRAM_API_KEY=9dc3d6e200e4386194dc4706b059b74ad72a2ec2"
echo "     ELEVENLABS_API_KEY=sk_3df5010e43944901820d82e74128ed953a4c9321d3d93ce8"
echo "     ELEVENLABS_VOICE_ID=c9tXABmaj4sESRRQ4Uqo"
echo "     OPENAI_MODEL=gpt-4.1-2025-04-14"
echo ""
echo "Option B: From GitHub"
echo "- In Pipecat Cloud: Connect GitHub"
echo "- Select: dsactivi-2/Agents (main-deploy branch)"
echo "- Auto-builds and deploys"
echo ""
echo "Option C: Use provided Docker Hub"
echo "- Coming soon..."
