#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai_Responses (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""


from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams
from pipecat.services.openai.responses.llm import OpenAIResponsesLLMService
from pipecat.pipeline.runner import PipelineRunner
from pipecat.runner.types import DailyRunnerArguments
from pipecat.processors.aggregators.llm_context import LLMContext
import os
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.runner.types import RunnerArguments
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.transports.base_transport import TransportParams
from pipecat.pipeline.pipeline import Pipeline
from pipecat.services.elevenlabs.tts import ElevenLabsTTSService
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.frames.frames import LLMRunFrame, Language
from pipecat.transports.base_transport import BaseTransport
from dotenv import load_dotenv
from loguru import logger
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.daily.transport import DailyTransport, DailyParams

load_dotenv(override=True)




async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service (German telesales)
    stt = DeepgramSTTService(
        api_key=os.getenv("DEEPGRAM_API_KEY"),
        settings=DeepgramSTTService.Settings(
            model="nova-3",
            language=Language.DE,
            smart_format=True,
            punctuate=True,
            endpointing=300,
            utterance_end_ms=1200,
        ),
    )

    # Text-to-Speech service (ElevenLabs German)
    tts = ElevenLabsTTSService(
        api_key=os.getenv("ELEVENLABS_API_KEY"),
        settings=ElevenLabsTTSService.Settings(
            voice=os.getenv("ELEVENLABS_VOICE_ID") or "c9tXABmaj4sESRRQ4Uqo",  # Stefan Rank - Voice Agent Special (German)
            model="eleven_turbo_v2_5",
            language=Language.DE,
            stability=0.5,
            similarity_boost=0.75,
            style=0.3,
        ),
    )

    # LLM service (German telesales agent)
    german_system_prompt = """Du bist ein professioneller deutscher Telesales-Agent für eine innovative B2B-Lösung.

SPRACHE UND STIL:
- Sprich ausschliesslich Deutsch. Keine englischen Woerter.
- Formeller, warmer Ton. Siezen, nicht Duzen.
- Halte Antworten kurz und natuerlich (max 2-3 Saetze). Deine Antworten werden laut vorgelesen.
- Vermeide Fachjargon, erklaere Vorteile statt Features.
- Keine Emojis, Aufzaehlungszeichen oder Formatierung.

GESPRAECHSSTRUKTUR:
1. Begruessung: Kurz, warm, Anlass nennen
2. Bedarfsermittlung: Offene Fragen, aktiv zuhoeren
3. Angebot: Nutzen-Argumentation basierend auf Bedarf
4. Einwandbehandlung: Verstehen-Bestaetigen-Loesen
5. Abschluss: Klare Handlungsaufforderung

EINWANDBEHANDLUNG:
- "Zu teuer" → Wert hervorheben, monatliche Aufschluesslung
- "Muss darueber nachdenken" → Konkreten Grund erfragen, Vorteil wiederholen
- "Kein Interesse" → Respektieren, konkreten Nutzen nennen
- "Keine Zeit" → Verstaendnis zeigen, kurzen Folgetermin vorschlagen

UPSELL-TECHNIKEN:
- Cross-Selling: Ergaenzende Produkte vorschlagen
- Upgrade: Hoeherwertige Option mit Mehrwert praesentieren
- Bundling: Paketvorteile aufzeigen

VERBOTEN:
- Aggressiver Druck oder Manipulation
- Unwahre Aussagen
- Persoenliche Fragen
- Code-Switching, englische Woerter
- Mehr als 3 Saetze ohne Frage sprechen"""

    llm = OpenAIResponsesLLMService(
        api_key=os.getenv("OPENAI_API_KEY"),
        settings=OpenAIResponsesLLMService.Settings(
            model=os.getenv("OPENAI_MODEL", "gpt-4.1"),
            system_instruction=german_system_prompt,
        ),
    )



    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),    ),
    )


    


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        stt,

        user_aggregator,

        llm,

        tts,

        
        transport.output(),

        
        assistant_aggregator,

    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
        ],
    )

    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation in German
        context.add_message({"role": "user", "content": "Stelle dich vor und erklaere den Grund des Anrufs."})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()




    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case DailyRunnerArguments():
            transport = DailyTransport(
                runner_args.room_url,
                runner_args.token,
                "Pipecat Bot",
                params=DailyParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()